dist: trusty
language: java

rust:
  - stable

matrix:
  allow_failures:
    - os: osx
  include:
    - os: osx
      osx_image: xcode10
      script:
       - export JAVA_HOME=$(/usr/libexec/java_home)
       - mvn -f java/pom.xml clean install
       - RUST_TEST_THREADS=1 cargo build --manifest-path=rust/Cargo.toml
       - RUST_TEST_THREADS=1 cargo test --manifest-path=rust/Cargo.toml
    - os: linux
      jdk: openjdk8
      script:
       - mvn -f java/pom.xml clean install
       - RUST_TEST_THREADS=1 cargo build --manifest-path=rust/Cargo.toml
       - RUST_TEST_THREADS=1 cargo test --manifest-path=rust/Cargo.toml

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
