dist: trusty
language: java

rust:
  - stable

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      script:
       - export JAVA_HOME=$(/usr/libexec/java_home)
       - echo $JAVA_HOME
       - mvn -f java/pom.xml clean install
       - cargo build --manifest-path=rust/Cargo.toml
    - os: linux
      jdk: openjdk8
      script:
       - mvn -f java/pom.xml clean install
       - cargo build --manifest-path=rust/Cargo.toml

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
