dist: trusty
language: java

rust:
  - stable

jdk:
  - openjdk11
  - openjdk14
  - oraclejdk14

matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      script:
        - echo $JAVA_HOME
        - cargo clean --manifest-path=rust/Cargo.toml
        - cargo update --manifest-path=rust/Cargo.toml
        - J4RS_CONSOLE_LOG_LEVEL=debug cargo test --manifest-path=rust/Cargo.toml -- --nocapture
    - os: linux
      script:
        - echo $JAVA_HOME
        - mvn -f java/pom.xml clean install
        - cargo clean --manifest-path=rust/Cargo.toml
        - cargo update --manifest-path=rust/Cargo.toml
        - cargo test --manifest-path=rust/Cargo.toml

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
