dist: trusty
language: java
services: docker
os:
- linux
- osx

rust:
  - stable

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: linux
      jdk: openjdk8

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env

script:
  - echo $JAVA_HOME
  - mvn -f java/pom.xml clean install
  - cargo build --manifest-path=rust/Cargo.toml
