dist: trusty
language: java
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=j4rs

matrix:
  include:

    # Linux
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

rust:
  - stable
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env

install:
  - sh ci/install.sh

script:
  - mvn -f java/pom.xml clean install
  #- cargo build --manifest-path=rust/Cargo.toml
  - cd rust
  - bash ../ci/script.sh

after_script: set +e
